import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/Components/Footer";
import Hedar from "@/Components/heder_/Hedar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Buildecxo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Hedar />
        {children}
        
        <Footer />
      </body>
    </html>
  );
}
